apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBlBR2W94ZE7AxsDVU8X6RldwMN6UJusNUFNRw1MJH3CkQ1EmRHCZnzSeCsybXYVy3qoaHS8qXF9fl5fg5ikEPfYjNAcTdngsfwPrgTRmY9ilOXGqEhBzXRXOh1tdWn40oGubHyii9NfUyAGcbcCbd7sZMaUS6D+OvRV4qbZrDgC25bcoO7vwjy7gKwdkGsVhJqMKeh/VF47XNhGYfZ60d/XMRLMKMjc1TCo41Vtb4N3UhuIit+eIV7yVcgPc4TUUn3qKDiGWePgEcxBklDhSC5ZulSjor2QLmAvBks9v71yMYr0qea6ojkOgeV8LyPSTjQg9p5xVjmvTJvlX7E2J+Ch0LivYA6plNoLuwOoF2Db3f+elz2kXdSRoZn8nDQBaZWJFY8NQiABkgmAXDVLNIAzpFgMqnduAEextmdbwfM0OJ7dZvBGliPfVh3M8oyAPQ0HZPymB3K8EXKAKCCeNvXBAkNjFcYWuxAk8HRLDYfADeWr36G387FnVYLMKHt1Z27jbmY+zEODVf9UjtzMNkhBIJwqITSZmaNw4T9fAKlePWHQ5j7BNtaYtXuriUUjpiruprEb7zE9g6K7PEBnIU2wJ0CmEeVCeyLpS9SGVP6jEo1kuPeF6bvt7DOCUKvo3hfnFAk7afXyU3wfGdbnHa9YD+F2C9VC2KFKp4ncox1SKDYjwG0VQOzrxJ+7gUSpAyJFW872ZFyPIT9DipOtgnH1jxvlUmwIST25BPV+U7KXstbp3ROSHEbX9A8t/WCMbIH8Qdg6kZ8gXvjQVm+vXk8ymtuh+TY/hARkuQHw4sZrAeBVPcFx894nvQYEoLAGAdTASN8wA3uBoQRo62wC3qdbSDDanY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

