apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAdCuAnyEmvD+kt8wUTLAUHkwL8xY+wdRQPref+LNM7PcfkmtPfy35bpnXL3C3o1w4VDi9jh2AgpHzajZMlCYVsdh7GNwqXzJp5p/ZN0DJswr04WJYmp7UKc0lFnwJCI5O0bQssEtL3hqvAYSKhli6oO4AaWlgDfVGZ66DpnqX2U6L9NkIgp+MueQNoQ2Hfkoi1cHB2fkPs5MSXJuDPVECF0chXPKn+RpHnQR3xcg70EQjOD3/MPaZ+/E2cgXH1ZeIP8MHedRjZntTBW9dIBa64LtKUDdK3+X3CusGVfGbaPAm4xkX3NwYtjCDY2O8B/Q1ZZ5RS4mIBDeeYH3A643tsf4Au0aFixtycjpelTNkuq3jL97Vw4wKv1XdpqdCkbQIHYCqAkM/DJ4P1xQflbqoceaKoIyHu/WAx3brZgHuNuAMPMkAi8jtVnw7WFYJ/KylmucgEtdn52jRGnsNH9GXbLDZahSG8m7AnlJ3+j4k1uDxJJAH6r8CDXQ9mBoAuXwaSfHXQVqvpzqvvDTg7ggX2Hj+Rgc711nhDpTlibMqbnuxaiRzIiqCYHqN/JoD7+foacpElp7rDFssk5qvkpEf9JgKhOSsSzDgd2cMXsL29eTTbTn4W7thtTRf+3UyNOdETNiTCESgoE4j11lnPTO6bjVW38g/j3WZSsGhLLW6hreYspkg5PO1t1BDEEzz2LQi9jaDYntz8WTGDGHABXuPO7Ed45OzhrGv1RutO+72Ee2lhru366g0349kFy7I73TkAZTtNS4QWs7m/GnjQJ+6uGzcxyEGYwicT7T3c8BcJvMHbZ8sHZnCwPscMy/TEhwD0xvAe9t5Gqeo5QEwvnsNEWyNfcCM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

