apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgA9SudKmJD1cWGcM3+sf1bc6ytLsO6+ZhImzJgti27dxt9HWS2FTqDd414nzMLEb+T4iuqBrqSvmzluBj+Oac7t0ryda4Fe32mQNSnqP3Lh8cN7q+ZZTysJYji4wSKdfUok+4yeiN3xkaKfyRi1e7PdE1EseLz9uGaSFuCEfU27ZoLlOy3iNu4sFM8EzuXnti1JnE9EQS2aX359zPFKavX1skpJ0J/e7bnt9YH0xp7wVgIUEp/qYXT4dF4Ef81zW1VWI+vNLbiTP3FERIQyx/JycodINnbF5kgXQsjoTQg5QYwsCF4pGXzZCxR6CjW6zcsQGuT/nyy0CNRisaOackCJg2EpMj3Kp+XmiF+PgNeU+PdvAOBqRh+6h58p8vPxgKhyC/GUugm2ceeta8JG7A7h84HsF0iLBcOL0C+d/Aimosxlc2no56X+kRDsP4PeGObL2UGYLeF9xDSx4tfN8EEt246xLz6Et1osqkGR1SvlJE9tueuf1oCtALD9FPt5/102Aftk/kZO94Es0mw1lqrUmwC9vUT35AgVq1V6AM/B272CJCmC3cteW+DxXDpJL+Wi2M4bqZy66PIlvL59MdVSTrBKhJZ6FXRr0Ii6k6vFMRCxHKUZbq2VF7nSzY6sELFJQ1sxt+OcwQUYgyEXX41iMQJXVq4byUiTJOrwe48MJU2LcInYwUdnWH2NRCPi2MkQ7Hnvk0Kq8OkZaob2B8Dw2Xmz1eLcbOie14WtFVXr2YwSayqHfLgWoHMVlSCaH5+RpNW3ZDmDVe7IBaojH/dmqzPKrMDHH6Iu4/fzjIINKuqnUgFI1Yp8vo9rNnK7cOP9dBkf5FKEgPMNVCykRoOeWQyYl6U=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

