apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB4Ltz1GCzR5gxj5jDBQFrdMZvHL/2xfI+XxrOwMsPCnxHLlvmBC1EJAV7xCYTpwhCbVzwa/qW+qfiD6vRtXG2vWef8Bku4j8ZN/tsgYWQyNHEGA/ecoZUP9MVu2Qjv7gVhSwasql+XWwpSnNT4yHz0o9FOsJAcVhalcMBe9fES4+bH80j+qtgFXnW5RN8xXi5CS+7fMOaWedBmR2Wt4IH5ycCxPedKNOOnJwaxpbJgf//c2vpj7r28pfBI3FAYT6XUc//HRkZM2QzAxSTFitzumZXIYoEh0MhsUjDAFhTuZO6tLhGYCpM00PVa3zs7fP3MuwKt/DL+QRsxKLSWHUFnm9LSdYJN+eQl/W4ex/WVpX890cRuKwrxgrebPPzzLNPseP/MUMs9faH6QJp2OxZPQKFdsC1hTIYqn9G2iZRWdLgXBQQo6oPrC+KMtj4i+R/WayE/u183Rj6zxnxSztUnX21Vtd4k4hdNTOH+qZXrQ9tqU3KX5nCheWvvNr/BAAKfZz7ZKsrbjOGV3bEV+5miXkZIsKvlDp1OKZ8/HFgoesAL1rEtPhc5x3kPV5CdpXoI6RIqQfzvkqUKmq/lRVWyJPnq5KYjyoQ3oP4jG+tFO+t5iTskix7x8X3+2C8TkZZGBorJhQDNWCsIauJzUkT79ZJxwS5sk890lLf+iYAoVJQG84tu411syyt3eH4tr1pfH9G/8uB95YQv0FT4OvZxT6MMS2Xv3T9yyEiaXcPpLuiqRltyxaFWYtYhHtHErs64Eu/8KpRDhSOXRnt1gRJWN6qxefTqVZzzk4QfOAjmYFWOsXs7VwWab+H1q0Jj8LVyNYUv+D+eIfcLlYap6QXUx35itk4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

