apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB4M/JC7gb54WVkAFAwZHBN+H4GegzBtErxqeo9gVPtX8T6/HDFxaym3/o45lHW3Kb4VWKsjKvYpeIzOmlNS0MLwAd8/wmokLwDe/wNz0n5w9pObMmblXNSQByxZeoPKrxZJAdvEsBr34+bFF6P4DjRUnr43RvawnuuJZw7ctpzED7s8gxm5o7S8dH/ccVt8pMhyy5bBdTfJp5nrxf3y0VO+C+CIVOJiZWW41wAELUR+GMWWb3o1FckINb6qWbO/bo8amtQhPR7dXPb2evPa5po+eYCVjLdD/ty6ZIaPS9VQLk4m7ryB5i8bLFN6RUBhX9ZhgWB2vbAn9ze9lm4gDG/l5WKpbayHg4jAPOdbRnCXpMbdUOjpcc5c96tjrvLBNYciZjP1v321tkk10AhDTe357+/sbN7dPTc2NzpC0fsywdyZZimFe+wAb/aVkPaLRYIswj0VuaJZ0uozatTuwdI3iSGzyzTBZp6XHfuDkZhaEt2iPCkrDDxMI1EP1t5e1JsU6MTl6ATFZ+ojvG1EQ8NOquERgGxixIOllfdl1KCG9++NTu8bhaejRH1hIG7aIbbUv1CtMzWX6HtrKP2v/0xf1SidNG5jNIwuRDhMD1MuQDfzGku1z7n+mIkTllWel2EjUsTMYfmtpZAoIfji4UfVI9Hx8He07VjWd62Bi0XeJDw1nsTG3i5GyyWX7yMXgEkC4Z7qW9MVZJlPPxVyWYJED/7rYbj883WAJs3BU5MSA0h4vVXryWCl1ZDZAU/42EpfQyl1xlX/KzLeOHKjeQUpbEdt84ATUBwOfR1CfrO4J9TAvPNtW+7S/Sgpfo6Xng9WDJ2h5LfJL0WaSRC94J5sKzFjqU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system
