apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCmdPxNnDSWUTIpCO9oB3RmIuFXra/FGaeMAtzpruyYmDni2/CAr80u+SHS7QvYBkOFq5k/zNECAMisgukpnXC4aLGoTOf4Z6asesCG8F5WG2xze+722uQxlpB6M6je9ay+NP461Rbd6RGiGq2kftJ7cm5kh1Q41OE4xtPBV9x5tZTph2iEr7kdbBkPsjZJ0FuvPJVTtFD8luNF+6gM8Q41d+X7CCwzo6pRW9PpnXhGYTveChkHncSwPY3Xw0YTVbh1HuJ+BhBnHQ8vl36CUoOvDEYnRFN5HGuz9Rygv4GhOufnplDCWGvO63yzZib5q7ia57PZVdFxzJOIXsIoHZn4aYDm+qp4l4VjwC4fQlx4Ou3qDoTHYiYu9qOEURGqJ/tmXbOgwq0100q1VTW6m94OaUAOa+wD6SDTDl6qBj2rrl2jvBW85obUCJkDO0arBb8KbP1ZmOmLDUM5UhOILQXecKmBKiZ1iS1kKpNN8wUc9YYHmi/3mel+UqdD0R7Ya4Ms89yWGZxXf6tLhhIoYo/v6g+y8w5IeuEUH+T/iB2JK5tEBYGuwXTg0n2gLd5qADVdbWTZEI9WF+yFKZ3wQYZkPFnYzeOGt6AJAqZUT02P1cikrvU7VbFXx6NeegisjkwcBbko7RQWCLP1tfR1hVpWNig2qNxdO2UAJDZzAoi1YhYmQ760lLxFeb/tfK98qr2VJ30Ina+Yj2SpUEUa+Fj2kSw6DsEyGoD8AV70GxgMP861Z3tr4F8RBtHtUVrWpYEdvyTkU6T/fobwKFPipgcEIV8BxSCYKoyeLPDa9OyhZRWqMKsYAv2cS9VzCsenuUgBOkLkLcqxdoXCULq82qoTTOjZRUA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

