apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: argocd
spec:
  encryptedData:
    creds: AgAAgXzrTnG+qT7e71dMEPnduTTx8kSE5554Ared4oC68kaY2LjkQe0eH82qsYDq587cX7u1rifjvUdjb9kLPEVuLN8MGLWMpe7ZATy6x6/p5qzBdAzGjwlN+M1gS54fnhTrD/2pn4fyJxJVLCH5hZSH6pICO6WF2kdAfI+UBu/ZZPnVERbx2bmVm7k6IYBMzuaQOsKCa1jojreOiAjItwnVxQ3eD6iey4dpqWF83//Ts4rsYZOSVtTbyE0ABJGDUAsVrAYA+SYG5e+oSWn+pgjbkF2oYv5C9/vmloRcWUD4hm0/0IaeYHimeARUtMjEtnRsPtyQzRXFgiLEWMo3Czmqb6JOip4yHaeHT6IigqCsR7slaqrR/+f4UkLt2yOmSU5SWNsAAFHfWIKQNeVq/URsS/+LbgLWjbi52Kn4k4aL65/4WBITUKqY1ZOo1lAuLL0T8uV8leLJezzUuicN0bLCFJyxLkhzz6qMD4TDfteHOH10iOtDzEm/aSdFl8Vw7IDE4qTlgXz78fV3vpuBKLP9xDWA/61m0+rp09Ox1aTpAvl/D8FE4dFi9PzkYb4LPgWbVI3+Jre8tPdxb/8wymKfHOiPxNqQ/mtixxTYzQ6TqZ859JREvU444EkjVo4EUi+KEWP30XdXMfqkcrg16a5EjDppHz8H8GqhUUcguDOEGtte0Eet3/o5ref3fL564B3KwoHzzvxg7Ur6dj2m+TcOP9Qp6RL8qTzN2A9jKl+az+C38rx/gDTsIvPVL+vWy7pzyVBq/MnkDrPFIfAdQPSaPBnoWoXHGZq+YH1ub75R7BdKCM5v31k9zTkaNJZC/nBESXkcE/BIOiPtoykt4PFAzn4P5Lo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: argocd

