apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: argocd
spec:
  encryptedData:
    creds: AgCM7fKLd/t39406FLxRfNfZE1LgfcPYxPy6o22cXBArDomTb2Wh3K4hzmxignflSXG6Cd8ud9phD/kzIzVanGc02l15gJCqzZA3WjuSRiicVDYhY2LZvRQtQ+vN6ar+2bHOpt4JrukHyfaiAEXinsZBkasektzVlD7OgMvRbvTQ+mNL11r8+04SgBj8LtxO2m4ZMLwmQWdwxv2NZR3urvC8FXqNWBBPzu0p9kKXUyFk7tj+zJHzIM20haRzNJrVs4ag0k3B7oIFSyHSPXQ135zSXAgMvwrpIbP0lZYBrIAqxQgQC4G8cLEtr3X7f6pSBs9bTXDa6dg8g8rq/Ce1ZjqyLNQT9OOPixi1FxkW1601omMi9ZNl2Rtc73HHsSJGPr4j/fo7ZAjdd+aA02laZp2cVVXD3vQ0CwUFzw96mau+aGeC7SyuNFYp1ZjvTg77F0yCIL4tkmNVAKWkp6SEWhnRb0Gi77szu7vsFVI4n/AMwvbbHf+LVSLbtcJL9fRskpEVfnHzapJaCCCuCjBkZQXvCSViVPB5QAVnaJd1UlGerh6I9deE28QFkRMIxg7fzzMEF45UB+TwXdXKFCKDIpaZfuo6pCoY7d6cpLESPJSvj741efthKog4jX9U4/xE3BAfdbzPsmR7BdHkDJw5+adAP1lKZcZtaTNwYAG57l+4s5QC8y9Bf4Jx7x5cSitnvBgLFOhboybsEM5YHVui7reaDVR599GObjYl+Su4FEvROeFzqZf9vst4O5mRt2wHkSYR/3M4QeK7NZLVMEAf/ccS13SOFmGcQxwaF1oxj00RX4fyXxFZVd//DHG8ZcIWJLcfpB35o7H7mIHy9pg9X+zgsC0e5l0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: argocd

