---
# AWS PROVIDER CONFIG
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: argocd
      name: aws-creds
      key: creds
