apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCMkyKNklgXOewTKly8rUL38CT9bO8SxZhHaUolHwMTVlz2YxXss5SevPPT0nxUbvIC6igHTxSD44YsEa0G0HiDgGlOSRdJN8tTVWKH54eMJICNhEyS6q11YP7VO2xkIQeN7n59P7/A+UVD0N6PrdzfsDP080Gd46vVsSzm5taIPwlrPNtzeIZsK7bF7qHWAv0MjLt/vB9bJ+qYT8s8EOendFkqXtKYpn8cRxGH9NRc7rpro+tdy9AmVk2RjB3FCuDJEf2Vq/1JxgXkzwIjJTnW53NSddVegyhEmsKKE2e9FIV8qut1hp9YOHApF9vui3ZTQOiCtPxMeVCm+HlTSw+sCvIMCDO4hG3UMLJc/eyMwdk2SxwGuDFdD7yoT8RqyxLw4f11RjXKArqzhAOQ82Gx6SQhkXFSpEHaN/6BNMczEY3+wTwLSiTT0jPHBg3YElFPQhAzVcFdBxGKRyYaAIYpbjwZ5UCX3W5k0LhrE3cN4uwXr1QDSMMMFILAke99ita6q6a6fnCojVBxMvlcOXL6mPBlkuL8g+ebtPi2dvbpf6wxyJ69cqUZC048cmUhS7FeDaCP/RF9jGIN5b8mjCTxlDRXnE4RbLyxqtfAge84HHu6rBCMXp17/xapgrewQqAqNhooCyzuHN/SzkNJ3tTM9FR5+N0bVKLPrEJB24hZSgeNvaUug9ezonkYTKJPVyAQJG1unE0WpKhPLnAdcyQYWu6LN1oT20ptbIFLbHpxx5WOv59uxdB3zcE0247xnNhsSD7S14e1PAfzXq7aXUd2IsnHc24K3WWxKYd2KEd3fFMB0D6X5JXixjQe4bvZkQog/hLeXZ1OVh6JG6A8PaFpgStcuww=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

