---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 5k-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 5k-core
  source:
    repoURL: https://github.com/armenr/k3d-local-demo
    targetRevision: HEAD
    path: 5k-core
  destination:
    server: https://kubernetes.default.svc
    namespace: 5k-core
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
