apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-clusters
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 5k-core
  source:
    path: deployments/core-clusters
    repoURL: https://github.com/armenr/k3d-local-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
